### PR TITLE
Add snapshot testing in travis build, bitbucket pipeline, and update some snapshot testings.

### PR DESCRIPTION
**Pull request by rk-fsdev**

### CODE REVIEW

**Comment by afoerster** [comment]
@shafi1379 please review.
@rk-fsdev this needs a merge

**Review by afoerster — APPROVED** [review]
LGTM

**Review by shafi1379 — COMMENTED** [review]
@rk-fsdev Why we have modified `sagas.test.ts` into `sagas.test`. Is it for excluding from npm test ?.

**Comment by afoerster** [comment]
@shafi1379 do you approve this? @rk-fsdev looks like he has an outstanding question above.

**Comment by rk-fsdev** [comment]
> @rk-fsdev Why we have modified `sagas.test.ts` into `sagas.test`. Is it for excluding from npm test ?.

@shafi1379 , @afoerster , I changed it to `sagas.test`, because currently the saga testing is not working. We are gonna test all the test files in the build version, thus I temporarily remove that saga test.

**Pull request merged**
