### PR TITLE
Allowing to process simple template with empty processing section

### PR DESCRIPTION
**Pull request by martin-morek**
Changed parameters max-cores and max-memory for yarn to be optional

### CODE REVIEW

**Comment by afoerster** [comment]
@martin-morek is this ready to merge? Seems to me you still needed to make changes

**Comment by afoerster** [comment]
To a query

**Comment by martin-morek** [comment]
I think it's ready to go or what do you think is missing?

**Review by afoerster — APPROVED** [review]
LGTM

**Pull request merged**
